package registerinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-01-24T15:26:47.792+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://RegisterInterface/", name = "RegisterInter")
@XmlSeeAlso({ObjectFactory.class})
public interface RegisterInter {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://RegisterInterface/", className = "registerinterface.Register")
    @WebMethod
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://RegisterInterface/", className = "registerinterface.RegisterResponse")
    public java.lang.Boolean register(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
