package com.demo.content;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-11-08T15:21:54.397+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "ContentFacadeImp", 
                  wsdlLocation = "http://127.0.0.1:9000/ContentFacadeImp?wsdl",
                  targetNamespace = "http://Content.demo.com/") 
public class ContentFacadeImp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://Content.demo.com/", "ContentFacadeImp");
    public final static QName ContentFacadeImpPort = new QName("http://Content.demo.com/", "ContentFacadeImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:9000/ContentFacadeImp?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ContentFacadeImp.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:9000/ContentFacadeImp?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ContentFacadeImp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ContentFacadeImp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContentFacadeImp() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ContentFacadeImp(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ContentFacadeImp(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ContentFacadeImp(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ContentFacadeInter
     */
    @WebEndpoint(name = "ContentFacadeImpPort")
    public ContentFacadeInter getContentFacadeImpPort() {
        return super.getPort(ContentFacadeImpPort, ContentFacadeInter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContentFacadeInter
     */
    @WebEndpoint(name = "ContentFacadeImpPort")
    public ContentFacadeInter getContentFacadeImpPort(WebServiceFeature... features) {
        return super.getPort(ContentFacadeImpPort, ContentFacadeInter.class, features);
    }

}
