package com.demo.content;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-11-08T15:21:54.361+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://Content.demo.com/", name = "ContentFacadeInter")
@XmlSeeAlso({ObjectFactory.class})
public interface ContentFacadeInter {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getContent", targetNamespace = "http://Content.demo.com/", className = "com.demo.content.GetContent")
    @WebMethod
    @ResponseWrapper(localName = "getContentResponse", targetNamespace = "http://Content.demo.com/", className = "com.demo.content.GetContentResponse")
    public com.demo.content.RetContentBean getContent(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
