package com.demo.analysis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-11-08T15:21:52.136+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://Analysis.demo.com/", name = "AnalysisCommandInter")
@XmlSeeAlso({ObjectFactory.class})
public interface AnalysisCommandInter {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFilePath", targetNamespace = "http://Analysis.demo.com/", className = "com.demo.analysis.GetFilePath")
    @WebMethod
    @ResponseWrapper(localName = "getFilePathResponse", targetNamespace = "http://Analysis.demo.com/", className = "com.demo.analysis.GetFilePathResponse")
    public java.lang.String getFilePath(
        @WebParam(name = "arg0", targetNamespace = "")
        com.demo.analysis.FileType arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "fixCommand", targetNamespace = "http://Analysis.demo.com/", className = "com.demo.analysis.FixCommand")
    @WebMethod
    @ResponseWrapper(localName = "fixCommandResponse", targetNamespace = "http://Analysis.demo.com/", className = "com.demo.analysis.FixCommandResponse")
    public java.lang.String fixCommand(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFileType", targetNamespace = "http://Analysis.demo.com/", className = "com.demo.analysis.GetFileType")
    @WebMethod
    @ResponseWrapper(localName = "getFileTypeResponse", targetNamespace = "http://Analysis.demo.com/", className = "com.demo.analysis.GetFileTypeResponse")
    public com.demo.analysis.FileType getFileType(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
