package com.demo.analysis;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-11-08T15:21:52.174+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "AnalysisCommandImp", 
                  wsdlLocation = "http://127.0.0.1:9000/AnalysisCommandImp?wsdl",
                  targetNamespace = "http://Analysis.demo.com/") 
public class AnalysisCommandImp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://Analysis.demo.com/", "AnalysisCommandImp");
    public final static QName AnalysisCommandImpPort = new QName("http://Analysis.demo.com/", "AnalysisCommandImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:9000/AnalysisCommandImp?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AnalysisCommandImp.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:9000/AnalysisCommandImp?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AnalysisCommandImp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AnalysisCommandImp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnalysisCommandImp() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AnalysisCommandImp(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AnalysisCommandImp(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AnalysisCommandImp(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AnalysisCommandInter
     */
    @WebEndpoint(name = "AnalysisCommandImpPort")
    public AnalysisCommandInter getAnalysisCommandImpPort() {
        return super.getPort(AnalysisCommandImpPort, AnalysisCommandInter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnalysisCommandInter
     */
    @WebEndpoint(name = "AnalysisCommandImpPort")
    public AnalysisCommandInter getAnalysisCommandImpPort(WebServiceFeature... features) {
        return super.getPort(AnalysisCommandImpPort, AnalysisCommandInter.class, features);
    }

}
