package registerimplement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import registerinterface.RegisterInter;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-01-24T15:26:47.843+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "RegisterImp", 
                  wsdlLocation = "http://127.0.0.1:9001/RegisterImp?wsdl",
                  targetNamespace = "http://RegisterImplement/") 
public class RegisterImp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://RegisterImplement/", "RegisterImp");
    public final static QName RegisterImpPort = new QName("http://RegisterImplement/", "RegisterImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:9001/RegisterImp?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegisterImp.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:9001/RegisterImp?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RegisterImp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegisterImp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegisterImp() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RegisterImp(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RegisterImp(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RegisterImp(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RegisterInter
     */
    @WebEndpoint(name = "RegisterImpPort")
    public RegisterInter getRegisterImpPort() {
        return super.getPort(RegisterImpPort, RegisterInter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegisterInter
     */
    @WebEndpoint(name = "RegisterImpPort")
    public RegisterInter getRegisterImpPort(WebServiceFeature... features) {
        return super.getPort(RegisterImpPort, RegisterInter.class, features);
    }

}
