package com.demo.menu;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-11-08T15:21:49.757+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://Menu.demo.com/", name = "MenuInter")
@XmlSeeAlso({ObjectFactory.class})
public interface MenuInter {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "GetMenu", targetNamespace = "http://Menu.demo.com/", className = "com.demo.menu.GetMenu")
    @WebMethod(operationName = "GetMenu")
    @ResponseWrapper(localName = "GetMenuResponse", targetNamespace = "http://Menu.demo.com/", className = "com.demo.menu.GetMenuResponse")
    public java.lang.String getMenu();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "Analysis", targetNamespace = "http://Menu.demo.com/", className = "com.demo.menu.Analysis")
    @WebMethod(operationName = "Analysis")
    @ResponseWrapper(localName = "AnalysisResponse", targetNamespace = "http://Menu.demo.com/", className = "com.demo.menu.AnalysisResponse")
    public java.lang.String analysis(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
