package com.demo.menu;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-11-08T15:21:49.815+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "MenuImp", 
                  wsdlLocation = "http://127.0.0.1:9000/MenuImp?wsdl",
                  targetNamespace = "http://Menu.demo.com/") 
public class MenuImp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://Menu.demo.com/", "MenuImp");
    public final static QName MenuImpPort = new QName("http://Menu.demo.com/", "MenuImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:9000/MenuImp?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MenuImp.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:9000/MenuImp?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MenuImp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MenuImp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MenuImp() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MenuImp(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MenuImp(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MenuImp(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MenuInter
     */
    @WebEndpoint(name = "MenuImpPort")
    public MenuInter getMenuImpPort() {
        return super.getPort(MenuImpPort, MenuInter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MenuInter
     */
    @WebEndpoint(name = "MenuImpPort")
    public MenuInter getMenuImpPort(WebServiceFeature... features) {
        return super.getPort(MenuImpPort, MenuInter.class, features);
    }

}
